//bai2
const friends = [`Linh`,`Thư `,` Phương`];
friends.push(`Đào`);
console.log(friends.length);
console.log(`người bạn đầu tiên ${friends[0]} `);

//bai1/
// let carts = [`thanh long`,` bảng vẽ `, ` phấn mắt`, `eyeliner`, ` tăm nước`, `chỉ nha khoa `, ` thuốc đỏ`, ` bông tẩy trang`];

//các pthuc:
//   carts.push(`a`); //thêm cuối
//   carts.pop();//xóa cuối
//   carts.unshift(`b`); //thêm đầu
//   carts.shift();//xóa đầu
//   carts.splice(2,3); //?:optional, [-]: xóa hết; 3: xóa 3 ptu
//   carts.splice(2,0,`bep`) // 0: không xóa; chèn `bep`/
 
//console.log(`tổng số món hàng ${carts.length}`);
// console.log(`món hàng 1 ${carts[0]}`);
// console.log(`món hàng cuối ${carts[carts.length -1]}`);

// mảng lồng nhau:
// console.log(matrix[1][2][3]); //hộp 1, trong hộp 1 lấy hộp vị trí số 2, trong hộp đó lấy ptu ở vtri số 3